#!/usr/bin/env bash

# Error handling
set -eEuo pipefail
trap 'printf "\n%s\n" "💥 Error on line ${LINENO} while running${asset:+ [${owner}/${repo}/${asset}]}: ${BASH_COMMAND}" >&2; exit 1' ERR

if (( BASH_VERSINFO[0] < 4 ||
      (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4) )); then
  printf '%s\n' 'This script requires Bash 4.4+'
  false # fire the trap
fi

# Shell options
shopt -s extglob
shopt -s nullglob
shopt -s expand_aliases

# Script directory and arguments
SCRIPT_DIRNAME="$(cd "$(dirname "${0}")" && pwd)"
SCRIPT_ARGS=("${@}")

# github token (recommended)
# https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api#primary-rate-limit-for-unauthenticated-users
# => unauthenticated : 60 requests per hour
# => authenticated   : 5,000 requests per hour
if [[ -n ${GHTCLI_GITHUB_TOKEN:=${GITHUB_TOKEN-}} ]]; then
  AUTH_HEADER="Authorization: Bearer ${GHTCLI_GITHUB_TOKEN}"
else
  AUTH_HEADER=''
fi

# Target folders
if [[ $(id -u) -eq 0 ]]; then
  # all users of the system
  mkdir -p /var/cache/ghtcli; cd $_                       # work-dir
  mkdir -p /etc/ghtcli; CFG_PATH=$_                       # config-path
  mkdir -p /usr/local/bin; BIN_PATH=$_                    # binary-path
  mkdir -p /usr/local/libexec; LIBEXEC_PATH=$_            # libexec-path
  mkdir -p /etc/fish/completions; FCD_PATH=$_             # fish-completion
  mkdir -p /etc/bash_completion.d; BCD_PATH=$_            # bash-completion
  mkdir -p /usr/share/zsh/vendor-completions; ZCD_PATH=$_ # zsh-completion
else
  # single user
  mkdir -p "${HOME}"/.cache/ghtcli; cd $_                                  # work-dir
  mkdir -p "${HOME}"/.config/ghtcli; CFG_PATH=$_                           # config-path
  mkdir -p "${HOME}"/.local/bin; BIN_PATH=$_                               # binary-path
  mkdir -p "${HOME}"/.local/libexec; LIBEXEC_PATH=$_                       # libexec-path
  mkdir -p "${HOME}"/.config/fish/completions; FCD_PATH=$_                 # fish-completion
  mkdir -p "${HOME}"/.local/share/bash-completion/completions; BCD_PATH=$_ # bash-completion
  mkdir -p "${HOME}"/.zsh/completion; ZCD_PATH=$_                          # zsh-completion
fi
PATH="${BIN_PATH}:${PATH}"

# Map to standard architecture names
declare -l ARCH
case $(uname -m) in
  x86_64)    ARCH='amd64' ;;
  x86|i386|i686) ARCH='386' ;;
  aarch64)   ARCH='arm64' ;;
  armv7*)    ARCH='armv7' ;;
  armv6*)    ARCH='armv6' ;;
  armv5*)    ARCH='armv5' ;;
  *)         ARCH="$(uname -m)" ;;
esac

# Kernel (Linux|Darwin|?)
# Other kernels are possible, but not all
# of the tools used here are built for them.
# For example, Freebsd.
declare -l KERNEL
KERNEL=$(uname -s)

# sed inplace-compatibility
if [[ ${KERNEL} == darwin ]]; then
  alias sed='sed -i ""'
else
  alias sed='sed -i'
fi

#
# Application groups and dependencies
#

# groups
_ghlr_aquasecurity=trivy
_ghlr_digitalocean=doctl
_ghlr_docker=ctop,lazydocker,dry,docuum
_ghtlr_git=lazygit
_ghlr_gitlab=glab
_ghlr_hashicorp=vault,terraform
_ghlr_kube=kubectl,kube_ps1,krew,kubectx,kubens,k9s,stern,kustomize,helm,helm_ct
_ghlr_lazy=lazydocker,lazygit
_ghlr_minio=mc,rclone
_ghlr_registry=oras,regclient,skopeo
_ghlr_security=trivy
_ghlr_image=dockle,dive,hadolint,mintoolkit
_ghlr_talos=talosctl,ttx,talos_ps1,talhelper,talm,flux

# dependencies
_ghlr_kubectx=fzf
_ghlr_kubens=fzf
_ghlr_regclient=regbot,regctl,regsync
_ghlr_ttx=fzf,yq

#
# Installable Applications
#

# ghtcli
_ghlr_ghtcli()
{
  local repo=ghtcli owner=marcel-buehr-ing asset=ghtcli
  case ${1} in
    install)
      local asset_url=ghtcli
      local asset_out='ghtcli-${asset_sha}'
      _latest_commit_raw_asset
      if [[ "$(basename ${BASH_SOURCE[0]})" == ghtcli ]]; then
        if [[ ${KERNEL} == darwin ]]; then
          msec=$(stat -f %m "${SCRIPT_DIRNAME}"/ghtcli)
        else
          msec=$(stat -c %Y "${SCRIPT_DIRNAME}"/ghtcli)
        fi
        if [[ $(( $(date +%s) - ${msec} )) -eq 0 ]]; then
          if ! _noninteractive; then
            printf '%s %s\n' \
              "${_clr_orange}ghtcli${_clr_reset}" \
              "${_clr_blue}reloading with updated version..${_clr_reset}"
          fi
          sleep 1s
          if [[ ${KERNEL} == darwin ]]; then
            exec $(which bash 2>/dev/null) "${SCRIPT_DIRNAME}"/ghtcli "${SCRIPT_ARGS[@]}"
          else
            exec "${SCRIPT_DIRNAME}"/ghtcli "${SCRIPT_ARGS[@]}"
          fi
        fi
      fi
      ;;
    postinstall) true ;;
    remove)
      _autoupdate disable
      rmdir -v "${CFG_PATH}" ||:
      _remove_asset
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# age-encryption
_ghlr_age()
{
  local repo=age owner=FiloSottile asset=age
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=tar.gz
      local asset_url='age-${asset_rel}-${KERNEL}-${ARCH}.${asset_ext#.}'
      local asset_out='age-${asset_rel}-${KERNEL}-${ARCH}'
      local asset_tar=age/age
      _latest_release_asset
      local asset=age-keygen
      local asset_tar=age/age-keygen
      _latest_release_asset
      ;;
    postinstall)
      true
      #age completion bash >"${BCD_PATH}"/age
      #age completion zsh >"${ZCD_PATH}"/_age
      #age completion fsh >"${FCD_PATH}"/age.fish
      ;;
    remove)
      _remove_asset
      rm -vf "${BIN_PATH}"/age-keygen
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# carapace
_ghlr_carapace()
{
  local repo=carapace-bin owner=carapace-sh asset=carapace
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${asset}-bin_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=carapace
      _latest_release_asset
      ;;
    postinstall)
      carapace carapace bash >"${BCD_PATH}"/carapace
      carapace carapace zsh >"${ZCD_PATH}"/_carapace
      carapace carapace fish >"${FCD_PATH}"/carapace.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# cert-manager-cli
_ghlr_cmctl()
{
  local repo=cmctl owner=cert-manager asset=cmctl
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_url='${asset}_${KERNEL}_${ARCH}'
      _latest_release_asset
      ;;
    postinstall)
      cmctl completion bash >"${BCD_PATH}"/cmctl
      cmctl completion zsh >"${ZCD_PATH}"/_cmctl
      cmctl completion fsh >"${FCD_PATH}"/cmctl.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# ctop
_ghlr_ctop()
{
  local repo=ctop owner=bcicen asset=ctop
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_url='${asset}-${asset_rel//[^0-9.]}-${KERNEL}-${ARCH}'
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# curl
_ghlr_curl()
{
  local repo=static-curl owner=stunnel asset=curl
  case ${1} in
    install)
      local CURL_CA_BUNDLE="${CURL_CA_BUNDLE:-/etc/ssl/certs/ca-certificates.crt}"
      if [[ ! -r "${CURL_CA_BUNDLE}" ]]; then
        printf '%s %s %s\n%s\n' \
          "${_clr_red}Ignored${_clr_reset}" \
          "${_clr_blue}curl${_clr_reset}" \
          "Certificate file not found: ${_clr_orange}${CURL_CA_BUNDLE}${_clr_reset}" \
          "💡 Set the correct path with ${_clr_orange}export ${_clr_blue}CURL_CA_BUNDLE='/path/to/ca-cert-bundle'${_clr_reset}" \
          >&2
        return
      fi
      local ARCH=${ARCH/amd64/x86_64}
      local KERNEL=${KERNEL/darwin/macos}
      local asset_ext=tar.xz
      if [[ ${KERNEL} == macos ]]; then
        local asset_url='${asset}-${KERNEL}-${ARCH}-${asset_rel//[^0-9.]}.${asset_ext}'
      else
        local asset_url='${asset}-${KERNEL}-${ARCH}-musl-${asset_rel//[^0-9.]}.${asset_ext}'
        local asset_out='${asset}-${asset_rel}-musl-${KERNEL}-${ARCH}'
      fi
      local asset_tar=curl
      _latest_release_asset
      hash -d curl
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# dive
_ghlr_dive()
{
  local repo=dive owner=wagoodman asset=dive
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=dive
      _latest_release_asset
      ;;
    postinstall)
      dive completion bash >"${BCD_PATH}"/dive
      dive completion zsh >"${ZCD_PATH}"/_dive
      dive completion fish >"${FCD_PATH}"/dive.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# dockle
_ghlr_dockle()
{
  local repo=dockle owner=goodwithtech asset=dockle
  case ${1} in
    install)
      local KERNEL=${KERNEL/linux/Linux}
      local KERNEL=${KERNEL/darwin/macOS}
      local ARCH=${ARCH/amd64/64bit}
      local ARCH=${ARCH/arm64/ARM64}
      local ARCH=${ARCH/armv*/ARM}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}-${ARCH}.${asset_ext}'
      local asset_tar=dockle
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# doctl
_ghlr_doctl()
{
  local repo=doctl owner=digitalocean asset=doctl
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${asset}-${asset_rel//[^0-9.]}-${KERNEL}-${ARCH}.${asset_ext}'
      local asset_tar=doctl
      _latest_release_asset
      ;;
    postinstall)
      if ! _noninteractive; then
        # fails in non-interactive mode due to cgroup checks
        doctl completion bash >"${BCD_PATH}"/doctl
        doctl completion zsh >"${ZCD_PATH}"/_doctl
        doctl completion fish >"${FCD_PATH}"/doctl.fish
      fi
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# docuum
_ghlr_docuum()
{
  local repo=docuum owner=stepchowfun asset=docuum
  case ${1} in
    install)
      local KERNEL=${KERNEL/linux/unknown-linux-musl}
      local KERNEL=${KERNEL/darwin/apple-darwin}
      local ARCH=${ARCH/amd64/x86_64}
      local ARCH=${ARCH/arm64/aarch64}
      local asset_url='${asset}-${ARCH}-${KERNEL}'
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# dry
_ghlr_dry()
{
  local repo=dry owner=moncho asset=dry
  case ${1} in
    install)
      local asset_url='${asset}-${KERNEL}-${ARCH}'
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# flux
_ghlr_flux()
{
  local repo=flux2 owner=fluxcd asset=flux
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=flux
      _latest_release_asset
      ;;
    postinstall)
      flux completion bash >"${BCD_PATH}"/flux
      flux completion zsh >"${ZCD_PATH}"/_flux
      flux completion fish >"${FCD_PATH}"/flux.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# fzf
_ghlr_fzf()
{
  local repo=fzf owner=junegunn asset=fzf
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${asset}-${asset_rel//[^0-9.]}-${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=fzf
      _latest_release_asset
      ;;
    postinstall)
      fzf --bash >"${BCD_PATH}"/fzf
      fzf --zsh >"${ZCD_PATH}"/_fzf
      fzf --fish >"${FCD_PATH}"/fzf.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# glab
_ghlr_glab()
{
  local repo=glab owner=gl-cli asset=glab
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_rel="$(curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} -fsSL https://api.github.com/repos/gl-cli/glab/tags |jq -r '.[0].name')"
      local asset_dwl='https://gitlab.com/gitlab-org/cli/-/releases/${asset_rel}/downloads/${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=bin/glab
      _latest_release_asset
      ;;
    postinstall)
      glab completion -s bash >"${BCD_PATH}"/glab
      glab completion -s zsh >"${ZCD_PATH}"/_glab
      glab completion -s fish >"${FCD_PATH}"/glab.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# hadolint
_ghlr_hadolint()
{
  local repo=hadolint owner=hadolint asset=hadolint
  case ${1} in
    install)
      local KERNEL=${KERNEL/darwin/macos}
      local ARCH=${ARCH/amd64/x86_64}
      local asset_url='${asset}-${KERNEL}-${ARCH}'
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# helm
_ghlr_helm()
{
  local repo=helm owner=helm asset=helm
  case ${1} in
    install)
      local ARCH=${ARCH/armv7/arm}
      local asset_ext=tar.gz
      local asset_tar='${KERNEL}-${ARCH}/${asset}'
      local asset_url='${asset}-${asset_rel}-${KERNEL}-${ARCH}.${asset_ext}'
      local asset_dwl='https://get.helm.sh/${asset_url}'
      _latest_release_asset
      ;;
    postinstall)
      helm completion bash >"${BCD_PATH}"/helm
      helm completion zsh >"${ZCD_PATH}"/_helm
      helm completion fish >"${FCD_PATH}"/helm.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# helm-chart-testing
_ghlr_helm_ct()
{
  local repo=chart-testing owner=helm asset=ct
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${repo}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=ct
      _latest_release_asset
      ;;
    postinstall)
      mkdir -p "${HOME}"/.ct
      local asset_path=$_
      local asset_url=etc/chart_schema.yaml
      local asset_out='ct-${asset//[.]/_}-${asset_rel//[^0-9.]}-${asset_sha}'
      local asset_cpf='ct-${asset//[.]/_}-*'
      local asset=chart_schema.yaml
      _latest_release_raw_asset
      local asset_url=etc/lintconf.yaml
      local asset_out='ct-${asset//[.]/_}-${asset_rel//[^0-9.]}-${asset_sha}'
      local asset_cpf='ct-${asset//[.]/_}-'
      local asset=lintconf.yaml
      _latest_release_raw_asset
      ct completion bash >"${BCD_PATH}"/ct
      ct completion zsh >"${ZCD_PATH}"/_ct
      ct completion fsh >"${FCD_PATH}"/ct.fish
      ;;
    remove)
      _remove_asset
      rm -vrf "${HOME}"/.ct
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# jq
_ghlr_jq()
{
  local repo=jq owner=jqlang asset=jq
  case ${1} in
    install)
      local ARCH=${ARCH/386/i386}
      local KERNEL=${KERNEL/darwin/macos}
      _latest_release_asset
      ;;
    postinstall)
      # jq completion bash >"${BCD_PATH}"/jq
      local repo=bash-completion owner=scop asset=jq
      local asset_url=completions/jq
      local asset_out='${asset}-${repo}-${asset_sha}'
      local asset_cpf='${asset}-${repo}-*'
      local asset_path="${BCD_PATH}"
      _latest_commit_raw_asset
      ;;
    remove)
      _remove_asset
      rm -vf "${BCD_PATH}"/jq-scop
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# k9s
_ghlr_k9s()
{
  local repo=k9s owner=derailed asset=k9s
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${asset}_${KERNEL^}_${ARCH}.${asset_ext}'
      local asset_tar=k9s
      _latest_release_asset
      ;;
    postinstall)
      k9s completion bash >"${BCD_PATH}"/k9s
      k9s completion zsh >"${ZCD_PATH}"/_k9s
      k9s completion fish >"${FCD_PATH}"/k9s.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# krew
_ghlr_krew()
{
  local repo=krew owner=kubernetes-sigs asset=krew
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=tar.gz
      local asset_url='${asset}-${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar='./krew-${KERNEL}_${ARCH}'
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# kube-ps1
_ghlr_kube_ps1()
{
  local repo=kube-ps1 owner=jonmosco asset=kube-ps1.sh
  case ${1} in
    install)
      local asset_branch=master
      local asset_url='${asset}'
      local asset_out='${asset}-${asset_sha}'
      local asset_path="${LIBEXEC_PATH}"
      rm -vf "${BIN_PATH}"/kube-ps1.sh
      _latest_commit_raw_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# kubectl
_ghlr_kubectl()
{
  local repo=kubectl owner=kubernetes asset=kubectl
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_rel="$(curl -fsSL https://dl.k8s.io/release/stable.txt)"
      local asset_dwl='https://dl.k8s.io/release/${asset_rel}/bin/${KERNEL}/${ARCH}/${asset}'
      _latest_release_asset
      ;;
    postinstall)
      kubectl completion bash >"${BCD_PATH}"/kubectl
      kubectl completion zsh >"${ZCD_PATH}"/_kubectl
      kubectl completion fish >"${FCD_PATH}"/kubectl.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# kubectx => ktx
_ghlr_kubectx()
{
  local repo=kubectx owner=ahmetb asset=ktx
  case ${1} in
    install)
      local ARCH=${ARCH/amd64/x86_64}
      local asset_ext=tar.gz
      local asset_url='kubectx_${asset_rel}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=kubectx
      _latest_release_asset
      ;;
    postinstall)
      # ktx completion bash >"${BCD_PATH}"/ktx
      local asset_url=completion/kubectx.bash
      local asset_out='ktx-bash-completion-${asset_rel}-${asset_sha}'
      local asset_cpf='ktx-bash-completion-*'
      local asset_path="${BCD_PATH}"
      local asset=ktx
      _latest_release_raw_asset
      sed 's/^\(complete -F _kube_contexts kubectx kctx\)$/\1 ktx/' \
        ktx-bash-completion-*-!(*.etag) "${BCD_PATH}"/ktx
      # ktx completion zsh >"${ZCD_PATH}"/_ktx
      local asset_url=completion/_kubectx.zsh
      local asset_out='ktx-zsh-completion-${asset_rel}-${asset_sha}'
      local asset_cpf='ktx-zsh-completion-*'
      local asset_path="${ZCD_PATH}"
      local asset=_ktx
      _latest_release_raw_asset
      sed 's/^\(#compdef kubectx kctx=kubectx\)$/\1 ktx=kubectx/' \
        ktx-zsh-completion-*-!(*.etag) "${ZCD_PATH}"/_ktx
      # ktx completion fish >"${FCD_PATH}"/ktx.fish
      local asset_url=completion/kubectx.fish
      local asset_out='ktx-fish-completion-${asset_rel}-${asset_sha}'
      local asset_cpf='ktx-fish-completion-*'
      local asset_path="${FCD_PATH}"
      local asset=ktx.fish
      _latest_release_raw_asset
      sed 's/kubectx/ktx/g' \
        ktx-fish-completion-*-!(*.etag) "${FCD_PATH}"/ktx.fish
      ;;
    remove)
      _remove_asset
      rm -vf "${BCD_PATH}"/ktx-kubectx
      rm -vf "${ZCD_PATH}"/_ktx-kubectx
      rm -vf "${FCD_PATH}"/ktx-kubectx.fish
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# kubens => kns
_ghlr_kubens()
{
  local repo=kubectx owner=ahmetb asset=kns
  case ${1} in
    install)
      local ARCH=${ARCH/amd64/x86_64}
      local asset_ext=tar.gz
      local asset_url='kubens_${asset_rel}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=kubens
      _latest_release_asset
      ;;
    postinstall)
      # kns completion bash >"${BCD_PATH}"/kns
      local asset_url=completion/kubens.bash
      local asset_out='kns-bash-completion-${asset_rel}-${asset_sha}'
      local asset_cpf='kns-bash-completion-*'
      local asset_path="${BCD_PATH}"
      local asset=kns
      _latest_release_raw_asset
      # kns completion zsh >"${ZCD_PATH}"/_kns
      local asset_url=completion/_kubens.zsh
      local asset_out='kns-zsh-completion-${asset_rel}-${asset_sha}'
      local asset_cpf='kns-zsh-completion-*'
      local asset_path="${ZCD_PATH}"
      local asset=_kns
      _latest_release_raw_asset
      # kns completion fish >"${FCD_PATH}"/kns.fish
      local asset_url=completion/kubens.fish
      local asset_out='kns-fish-completion-${asset_rel}-${asset_sha}'
      local asset_cpf='kns-fish-completion-*'
      local asset_path="${FCD_PATH}"
      local asset=kns.fish
      _latest_release_raw_asset
      sed 's/kubens/kns/g' \
        kns-fish-completion-*-!(*.etag) "${FCD_PATH}"/kns.fish
      ;;
    remove)
      _remove_asset
      rm -vf "${BCD_PATH}"/kns-kubens
      rm -vf "${ZCD_PATH}"/_kns-kubens
      rm -vf "${FCD_PATH}"/kns-kubens.fish
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# kustomize
_ghlr_kustomize()
{
  local repo=kustomize owner=kubernetes-sigs asset=kustomize
  case ${1} in
    install)
      # asset_rhel (.tag_name) = kustomize/v1.2.3
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^v0-9.]}_${KERNEL^}_${ARCH}.${asset_ext}'
      local asset_dwl='https://github.com/${owner}/${repo}/releases/download/${asset_rel}/${asset_url}'
      local asset_out='${asset}-${asset_rel//[^v0-9.]}-${KERNEL}-${ARCH}'
      local asset_tar=kustomize
      _latest_release_asset
      ;;
    postinstall)
      kustomize completion bash >"${BCD_PATH}"/kustomize
      kustomize completion zsh >"${ZCD_PATH}"/_kustomize
      kustomize completion fish >"${FCD_PATH}"/kustomize.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# lazydocker
_ghlr_lazydocker()
{
  local repo=lazydocker owner=jesseduffield asset=lazydocker
  case ${1} in
    install)
      local ARCH=${ARCH/amd64/x86_64}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL^}_${ARCH}.${asset_ext}'
      local asset_tar=lazydocker
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# lazygit
_ghlr_lazygit()
{
  local repo=lazygit owner=jesseduffield asset=lazygit
  case ${1} in
    install)
      local ARCH=${ARCH/amd64/x86_64}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL^}_${ARCH}.${asset_ext}'
      local asset_tar=lazygit
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# minio mc
_ghlr_mc()
{
  local repo=mc owner=minio asset=mc
  case ${1} in
    install)
      local ARCH=${ARCH/armv7/arm}
      local asset_url="${KERNEL}-${ARCH}/mc"
      local asset_dwl='https://dl.min.io/client/mc/release/${asset_url}'
      _latest_release_asset
      ;;
    postinstall)
      #SHELL=bash mc --autocompletion >/dev/null
      printf '%s\n' "complete -C ${BIN_PATH@Q}/mc mc" >"${BCD_PATH}"/mc
      SHELL=zsh mc --autocompletion >/dev/null
      SHELL=fish mc --autocompletion >/dev/null
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# MinToolkit
_ghlr_mintoolkit()
{
  local repo=mint owner=mintoolkit asset=mint
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local ARCH=${ARCH/amd64/}
      local asset_ext=tar.gz
      if [[ ${KERNEL} == darwin ]]; then
        local KERNEL=mac
        local ARCH=${ARCH/arm64/m1}
        local asset_ext=zip
      fi
      local asset_url='dist_${KERNEL}${ARCH:+_${ARCH}}.${asset_ext}'
      local asset_out='mintoolkit-${asset_rel}-${KERNEL}${ARCH:+-${ARCH}}'
      local asset_tar='dist_${KERNEL}${ARCH:+_${ARCH}}/${asset}'
      local asset_zip='dist_${KERNEL}${ARCH:+_${ARCH}}/${asset}'
      _latest_release_asset
      local asset=mint-sensor
      _latest_release_asset
      ;;
    postinstall) true ;;
    remove)
      _remove_asset
      rm -vf "${BIN_PATH}"/mint-sensor
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# nerdctl
_ghlr_nerdctl()
{
  local repo=nerdctl owner=containerd asset=nerdctl
  case ${1} in
    install)
      if [[ ${KERNEL} == darwin ]]; then
        printf '%s %s %s\n' \
          "${_clr_red}Ignored${_clr_reset}" \
          "${_clr_blue}nerdctl${_clr_reset}" \
          "Is not compatible with ${_clr_orange}macOS${_clr_reset}" \
          >&2
        return
      fi
      local asset_ext=tar.gz
      local asset_url='nerdctl-${asset_rel//[^0-9.]}-${KERNEL}-${ARCH}.${asset_ext}'
      local asset_out='nerdctl-${asset_rel}-${KERNEL}-${ARCH}'
      local asset_tar=nerdctl
      _latest_release_asset
      local asset=containerd-rootless.sh
      local asset_tar=containerd-rootless.sh
      _latest_release_asset
      local asset=containerd-rootless-setuptool.sh
      local asset_tar=containerd-rootless-setuptool.sh
      _latest_release_asset
      ;;
    postinstall)
      nerdctl completion bash >"${BCD_PATH}"/nerdctl
      nerdctl completion zsh >"${ZCD_PATH}"/_nerdctl
      nerdctl completion fsh >"${FCD_PATH}"/nerdctl.fish
      ;;
    remove)
      _remove_asset
      rm -vf "${BIN_PATH}"/containerd-rootless{,-setuptool}.sh
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# openbao
_ghlr_openbao()
{
  local repo=openbao owner=openbao asset=bao
  case ${1} in
    install)
      local ARCH=${ARCH/amd64/x86_64}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=bao
      _installed del openbao_hsm
      _latest_release_asset
      ;;
    postinstall)
      bao -autocomplete-install 2>/dev/null ||:
      ;;
    remove)
      bao -autocomplete-uninstall 2>/dev/null ||:
      _remove_asset
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# openbao-hsm
_ghlr_openbao_hsm()
{
  local repo=openbao owner=openbao asset=bao
  case ${1} in
    install)
      if [[ ${KERNEL} == darwin ]]; then
        printf '%s %s %s\n%s\n' \
          "${_clr_red}Ignored${_clr_reset}" \
          "${_clr_blue}openbao_hsm${_clr_reset}" \
          "Is not compatible with ${_clr_orange}macOS${_clr_reset}" \
          "💡 Use OpenBao without HSM support with ${_clr_orange}ghtcli ${_clr_blue}install ${_clr_red}openbao${_clr_reset}" \
          >&2
        return
      fi
      local ARCH=${ARCH/amd64/x86_64}
      local asset_ext=tar.gz
      local asset_url='${asset}-hsm_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_out='${asset}-hsm-${asset_rel}-${KERNEL}-${ARCH}'
      local asset_tar=bao
      _installed del openbao
      _latest_release_asset
      ;;
    postinstall)
      bao -autocomplete-install 2>/dev/null ||:
      ;;
    remove)
      bao -autocomplete-uninstall 2>/dev/null ||:
      _remove_asset
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# opentofu
_ghlr_opentofu()
{
  local repo=opentofu owner=opentofu asset=tofu
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=tofu
      _latest_release_asset
      ;;
    postinstall)
      tofu -install-autocomplete 2>/dev/null ||:
      ;;
    remove)
      tofu -uninstall-autocomplete
      _remove_asset
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# oras
_ghlr_oras()
{
  local repo=oras owner=oras-project asset=oras
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=oras
      _latest_release_asset
      ;;
    postinstall)
      oras completion bash >"${BCD_PATH}"/oras
      oras completion zsh >"${ZCD_PATH}"/_oras
      oras completion fish >"${FCD_PATH}"/oras.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# rclone
_ghlr_rclone()
{
  local repo=rclone owner=rclone asset=rclone
  case ${1} in
    install)
      local KERNEL=${KERNEL/darwin/osx}
      local ARCH=${ARCH/armv7/arm-v7}
      local ARCH=${ARCH/armv6/arm-v6}
      local ARCH=${ARCH/armv5/arm-v5}
      local ARCH=${ARCH/i386/386}
      local asset_ext=zip
      local asset_url='${asset}-${asset_rel}-${KERNEL}-${ARCH}.${asset_ext}'
      local asset_zip='${asset}-${asset_rel}-${KERNEL}-${ARCH}/${asset}'
      _latest_release_asset
      ;;
    postinstall)
      rclone completion bash "${BCD_PATH}"/rclone
      rclone completion zsh "${ZCD_PATH}"/_rclone
      rclone completion fish "${FCD_PATH}"/rclone.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# regbot
_ghlr_regbot()
{
  local repo=regclient owner=regclient asset=regbot
  case ${1} in
    install)
      local asset_url='${asset}-${KERNEL}-${ARCH}'
      _latest_release_asset
      ;;
    postinstall)
      regbot completion bash >"${BCD_PATH}"/regbot
      regbot completion zsh >"${ZCD_PATH}"/_regbot
      regbot completion fish >"${FCD_PATH}"/regbot.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# regctl
_ghlr_regctl()
{
  local repo=regclient owner=regclient asset=regctl
  case ${1} in
    install)
      local asset_url='${asset}-${KERNEL}-${ARCH}'
      _latest_release_asset
      ;;
    postinstall)
      regctl completion bash >"${BCD_PATH}"/regctl
      regctl completion zsh >"${ZCD_PATH}"/_regctl
      regctl completion fish >"${FCD_PATH}"/regctl.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# regsync
_ghlr_regsync()
{
  local repo=regclient owner=regclient asset=regsync
  case ${1} in
    install)
      local asset_url='${asset}-${KERNEL}-${ARCH}'
      _latest_release_asset
      ;;
    postinstall)
      regsync completion bash >"${BCD_PATH}"/regsync
      regsync completion zsh >"${ZCD_PATH}"/_regsync
      regsync completion fish >"${FCD_PATH}"/regsync.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# skopeo
_ghlr_skopeo()
{
  local repo=skopeo-binary owner=lework asset=skopeo
  case ${1} in
    install)
      _latest_release_asset
      ;;
    postinstall)
      skopeo completion bash >"${BCD_PATH}"/skopeo
      skopeo completion zsh >"${ZCD_PATH}"/_skopeo
      skopeo completion fish >"${FCD_PATH}"/skopeo.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# sops
_ghlr_sops()
{
  local repo=sops owner=getsops asset=sops
  case ${1} in
    install)
      local asset_url='${asset}-${asset_rel}.${KERNEL}.${ARCH}'
      _latest_release_asset
      ;;
    postinstall)
      sops completion bash >"${BCD_PATH}"/sops
      sops completion zsh >"${ZCD_PATH}"/_sops
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# stern
_ghlr_stern()
{
  local repo=stern owner=stern asset=stern
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=stern
      _latest_release_asset
      ;;
    postinstall)
      stern --completion bash >"${BCD_PATH}"/stern
      stern --completion zsh >"${ZCD_PATH}"/_stern
      stern --completion fish >"${FCD_PATH}"/stern.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# talhelper
_ghlr_talhelper()
{
  local repo=talhelper owner=budimanjojo asset=talhelper
  case ${1} in
    install)
      local asset_ext=tar.gz
      local asset_url='${asset}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_tar=talhelper
      _latest_release_asset
      ;;
    postinstall)
      talhelper completion bash >"${BCD_PATH}"/talhelper
      talhelper completion zsh >"${ZCD_PATH}"/_talhelper
      talhelper completion fish >"${FCD_PATH}"/talhelper.fish
      ;;
    remove) _remove_asset;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# talm
_ghlr_talm()
{
  local repo=talm owner=cozystack asset=talm
  case ${1} in
    install)
      local ARCH=${ARCH/386/i386}
      local asset_ext=tar.gz
      local asset_url='${asset}-${KERNEL}-${ARCH}.${asset_ext}'
      local asset_tar=talm
      _latest_release_asset
      ;;
    postinstall)
      talm completion bash >"${BCD_PATH}"/talm
      talm completion zsh >"${ZCD_PATH}"/_talm
      talm completion fish >"${FCD_PATH}"/talm.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# talos-ps1
_ghlr_talos_ps1()
{
  local repo=ttx owner=mikemrm asset=talos-ps1.sh
  case ${1} in
    install)
      local asset_url='${asset}'
      local asset_out='${asset}-${asset_sha}'
      local asset_path="${LIBEXEC_PATH}"
      rm -vf "${BIN_PATH}"/talos-ps1.sh
      _latest_commit_raw_asset
      sed 's/printf "$output"/printf '\''%b'\'' "$output"/' \
        talos-ps1.sh-!(*.etag) "${LIBEXEC_PATH}"/talos-ps1.sh
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# talosctl
_ghlr_talosctl()
{
  local repo=talos owner=siderolabs asset=talosctl
  case ${1} in
    install)
      _latest_release_asset
      ;;
    postinstall)
      talosctl completion bash >"${BCD_PATH}"/talosctl
      talosctl completion zsh >"${ZCD_PATH}"/_talosctl
      talosctl completion fish >"${FCD_PATH}"/talosctl.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# trivy
_ghlr_trivy()
{
  local repo=trivy owner=aquasecurity asset=trivy
  case ${1} in
    install)
      local KERNEL=${KERNEL/linux/Linux}
      local KERNEL=${KERNEL/darwin/macOS}
      local ARCH=${ARCH/386/32bit}
      local ARCH=${ARCH/amd64/64bit}
      local ARCH=${ARCH/arm64/ARM64}
      local ARCH=${ARCH/armv*/ARM}
      local asset_ext=tar.gz
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}-${ARCH}.${asset_ext}'
      local asset_tar=trivy
      _latest_release_asset
      ;;
    postinstall)
      trivy completion bash >"${BCD_PATH}"/trivy
      trivy completion zsh >"${ZCD_PATH}"/_trivy
      trivy completion fish >"${FCD_PATH}"/trivy.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# ttx
_ghlr_ttx()
{
  local repo=ttx owner=mikemrm asset=ttx
  case ${1} in
    install)
      local asset_url='${asset}'
      local asset_out='${asset}-${asset_sha}'
      _latest_commit_raw_asset
      ;;
    postinstall) true ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# terraform
_ghlr_terraform()
{
  local repo=terraform owner=hashicorp asset=terraform
  case ${1-} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=zip
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_dwl='https://releases.hashicorp.com/${asset}/${asset_rel//[^0-9.]}/${asset_url}'
      local asset_zip=terraform
      _latest_release_asset
      ;;
    postinstall)
      terraform -install-autocomplete 2>/dev/null ||:
      ;;
    remove)
      terraform -uninstall-autocomplete 2>/dev/null ||:
      _remove_asset
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# vault
_ghlr_vault()
{
  local repo=vault owner=hashicorp asset=vault
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=zip
      local asset_url='${asset}_${asset_rel//[^0-9.]}_${KERNEL}_${ARCH}.${asset_ext}'
      local asset_dwl='https://releases.hashicorp.com/${asset}/${asset_rel//[^0-9.]}/${asset_url}'
      local asset_zip=vault
      _latest_release_asset
      ;;
    postinstall)
      vault -autocomplete-install 2>/dev/null ||:
      ;;
    remove)
      vault -autocomplete-uninstall 2>/dev/null ||:
      _remove_asset
      ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# velero
_ghlr_velero()
{
  local repo=velero owner=vmware-tanzu asset=velero
  case ${1} in
    install)
      local ARCH=${ARCH/armv*/arm}
      local asset_ext=tar.gz
      local asset_url='${asset}-${asset_rel}-${KERNEL}-${ARCH}.${asset_ext}'
      local asset_tar='${asset}-${asset_rel}-${KERNEL}-${ARCH}/${asset}'
      _latest_release_asset
      ;;
    postinstall)
      velero completion bash >"${BCD_PATH}"/velero
      velero completion zsh >"${ZCD_PATH}"/_velero
      velero completion fish >"${FCD_PATH}"/velero.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

# yq
_ghlr_yq()
{
  local repo=yq owner=mikefarah asset=yq
  case ${1} in
    install)
      local asset_url='${asset}_${KERNEL}_${ARCH}'
      _latest_release_asset
      ;;
    postinstall)
      yq shell-completion bash >"${BCD_PATH}"/yq
      yq shell-completion zsh >"${ZCD_PATH}"/_yq
      yq shell-completion fish >"${FCD_PATH}"/yq.fish
      ;;
    remove) _remove_asset ;;
    clean) _clean_asset ;;
    info) _get_asset_info ;;
    *) false ;;
  esac
}

#
# Internal functions and vars
#

# Colors
_clr_red=$'\e[38;2;255;0;0m'
_clr_blue=$'\e[38;2;0;128;255m'
_clr_green=$'\e[38;2;0;200;0m'
_clr_orange=$'\e[38;2;255;106;0m'
_clr_reset=$'\e[0m'

# Installers
_latest_release_asset()
{
  # owner        : owner namespace (mandatory)
  # repo         : repo name (mandatory)
  # asset        : asset name (mandatory)
  # asset_tar    : asset name within tar archive  # default : ''
  # asset_zip    : asset name within zip archive  # default : ''
  # asset_ext    : asset file extension           # default : ''
  # asset_url    : asset name used in url         # default : ${asset}-${KERNEL}-${ARCH}${asset_ext:+.${asset_ext#.}}
  # asset_out    : asset name used as output      # default : ${asset}-${asset_rel}-${KERNEL}-${ARCH}
  # asset_rel    : asset release name             # default : $(curl -H "${AUTH_HEADER}" -fsSL "https://api.github.com/repos/${owner}/${repo}/releases/latest" |jq -r '.tag_name')
  # asset_dwl    : asset download url             # default : https://github.com/${owner}/${repo}/releases/download/${asset_rel}/${asset_url}
  # asset_cpf    : asset cache prune filter       # default : ${asset_out%%-*}-*
  # asset_dah    : asset download auth header     # default : ''

  # latest
  if [[ -z "${asset_rel-}" ]]; then
    if command -v jq &>/dev/null; then
      local asset_rel=$( \
        curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
          -fsSL "https://api.github.com/repos/${owner}/${repo}/releases/latest" \
          |jq -r '.tag_name'
      )
    else
      local asset_rel=$( \
        curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
          -fsSL "https://api.github.com/repos/${owner}/${repo}/releases/latest" \
          |awk -F\" '/"tag_name":/{print$(NF-1)}'
      )
    fi
  fi

  # custom asset_dwl doesn't get github token
  if [[ -n "${asset_dwl-}" ]]; then
    local AUTH_HEADER="${asset_dah-}"
  fi

  # download
  local asset_ext="${asset_ext-}"
  local asset_url="${asset_url-}"
  local asset_out="${asset_out-}"
  local asset_dwl="${asset_dwl-}"
  local asset_cpf="${asset_cpf-}"
  eval "asset_ext=\"${asset_ext}\""
  eval "asset_url=\"${asset_url:-${asset}-${KERNEL}-${ARCH}${asset_ext:+.${asset_ext#.}}}\""
  eval "asset_out=\"${asset_out:-${asset}-${asset_rel}-${KERNEL}-${ARCH}}\""
  eval "asset_dwl=\"${asset_dwl:-https://github.com/${owner}/${repo}/releases/download/${asset_rel}/${asset_url}}\""
  eval "asset_cpf=\"${asset_cpf:-${asset_cpf:-${asset}-*}}\""
  if curl --help http |grep -- '--etag-' &>/dev/null; then
    curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
         -fsSLR "${asset_dwl}" \
         --etag-save "${asset_out}${asset_ext:+.${asset_ext#.}}".etag \
         --etag-compare "${asset_out}${asset_ext:+.${asset_ext#.}}".etag \
         --time-cond "${asset_out}${asset_ext:+.${asset_ext#.}}" \
         --output "${asset_out}${asset_ext:+.${asset_ext#.}}"
  else
    curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
         -fsSLR "${asset_dwl}" \
         --time-cond "${asset_out}${asset_ext:+.${asset_ext#.}}" \
         --output "${asset_out}${asset_ext:+.${asset_ext#.}}"
  fi

  # extract
  local asset_tar="${asset_tar-}"
  local asset_zip="${asset_zip-}"
  if [[ -n "${asset_tar}" ]]; then
    eval "asset_tar=\"${asset_tar}\""
    tar -xf "${asset_out}${asset_ext:+.${asset_ext#.}}" \
        --strip-components=$(awk -F/ '{print(NF-1)}' <<<"${asset_tar}") \
        "${asset_tar}" 2>/dev/null
    mv -f "$(basename ${asset_tar})" "${asset_out}"
  elif [[ -n "${asset_zip}" ]]; then
    eval "asset_zip=\"${asset_zip}\""
    unzip -qoj "${asset_out}${asset_ext:+.${asset_ext#.}}" \
          "${asset_zip}" 2>/dev/null
    mv -f "$(basename ${asset_zip})" "${asset_out}"
  fi

  # install
  _install_asset
}

_latest_release_raw_asset()
{
  # owner        : owner namespace (mandatory)
  # repo         : repo name (mandatory)
  # asset        : asset name (mandatory)
  # asset_url    : asset name used in url     # default : ${asset}-${KERNEL}-${ARCH}
  # asset_out    : asset name used as output  # default : ${asset}-${asset_rel}-${KERNEL}-${ARCH}-${asset_sha}
  # asset_rel    : asset release name         # default : $(curl -H "${AUTH_HEADER}" -fsSL "https://api.github.com/repos/${owner}/${repo}/releases/latest" |jq -r '.tag_name')
  # asset_sha    : asset commit hash          # default : $(curl -H "${AUTH_HEADER}" -fsSL "https://api.github.com/repos/${owner}/${repo}/git/ref/tags/${asset_rel}" |jq -r '.object.sha[:7]')
  # asset_dwl    : asset download url         # default : https://github.com/${owner}/${repo}/releases/download/${asset_rel}/${asset_url}
  # asset_cpf    : asset cache prune filter   # default : ${asset_out%%-*}-*
  # asset_dah    : asset download auth header # default : ''

  # latest
  if [[ -z "${asset_rel-}" ]]; then
    local asset_rel=$( \
      curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
        -fsSL "https://api.github.com/repos/${owner}/${repo}/releases/latest" \
        |jq -r '.tag_name'
    )
  fi
  if [[ -z "${asset_sha-}" ]]; then
    local asset_ref=$( \
      curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
        -fsSL "https://api.github.com/repos/${owner}/${repo}/git/ref/tags/${asset_rel}" \
        |jq -r '.object.sha'
    )
    local asset_sha=$( \
      curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
        -fsSL "https://api.github.com/repos/${owner}/${repo}/git/tags/${asset_ref}" 2>/dev/null \
        |jq -r '.object.sha[:7]' || printf "${asset_ref::7}"
    )
  fi

  # custom asset_dwl doesn't get github token
  if [[ -n "${asset_dwl-}" ]]; then
    local AUTH_HEADER="${asset_dah-}"
  fi

  # download
  local asset_url="${asset_url-}"
  local asset_out="${asset_out-}"
  local asset_dwl="${asset_dwl-}"
  local asset_cpf="${asset_cpf-}"
  eval "asset_url=\"${asset_url:-${asset}-${KERNEL}-${ARCH}}\""
  eval "asset_out=\"${asset_out:-${asset}-${asset_rel}-${KERNEL}-${ARCH}-${asset_sha}}\""
  eval "asset_dwl=\"${asset_dwl:-https://raw.githubusercontent.com/${owner}/${repo}/${asset_sha}/${asset_url}}\""
  eval "asset_cpf=\"${asset_cpf:-${asset_cpf:-${asset}-*}}\""
  if curl --help http |grep -- '--etag-' &>/dev/null; then
    curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
         -fsSLR "${asset_dwl}" \
         --etag-save "${asset_out}".etag \
         --etag-compare "${asset_out}".etag \
         --time-cond "${asset_out}" \
         --output "${asset_out}"
  else
    curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
         -fsSLR "${asset_dwl}" \
         --time-cond "${asset_out}" \
         --output "${asset_out}"
  fi

  # install
  _install_asset
}

_latest_commit_raw_asset()
{
  # owner        : owner namespace (mandatory)
  # repo         : repo name (mandatory)
  # asset        : asset name (mandatory)
  # asset_tar    : asset name within tar file # default : ''
  # asset_branch : asset branch               # default : main
  # asset_url    : asset name used in url     # default : ${asset}-${KERNEL}-${ARCH}
  # asset_out    : asset name used as output  # default : ${asset}-(${asset_sha}-${KERNEL}-${ARCH}
  # asset_sha    : asset commit hash          # default : $(curl -H "${AUTH_HEADER}" -fsSL "https://api.github.com/repos/${owner}/${repo}/commits/heads/${asset_branch:-main}" |jq -r '.sha[:7]')
  # asset_dwl    : asset download url         # default : https://github.com/${owner}/${repo}/releases/download/${asset_rel}/${asset_url}
  # asset_cpf    : asset cache prune filter   # default : ${asset_out%%-*}-*
  # asset_dah    : asset download auth header # default : ''


  # latest
  if [[ -z "${asset_sha-}" ]]; then
    local asset_sha=$( \
      curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
        -fsSL "https://api.github.com/repos/${owner}/${repo}/commits/heads/${asset_branch:-main}" \
        |jq -r '.sha[:7]'
    )
  fi

  # custom asset_dwl doesn't get tokens
  if [[ -n "${asset_dwl-}" ]]; then
    local AUTH_HEADER="${asset_dah-}"
  fi

  # download
  local asset_url="${asset_url-}"
  local asset_out="${asset_out-}"
  local asset_dwl="${asset_dwl-}"
  local asset_cpf="${asset_cpf-}"
  eval "asset_url=\"${asset_url:-${asset}-${KERNEL}-${ARCH}}\""
  eval "asset_out=\"${asset_out:-${asset}-${asset_sha}-${KERNEL}-${ARCH}}\""
  eval "asset_dwl=\"${asset_dwl:-https://raw.githubusercontent.com/${owner}/${repo}/${asset_sha}/${asset_url}}\""
  eval "asset_cpf=\"${asset_cpf:-${asset_cpf:-${asset}-*}}\""
  if curl --help http |grep -- '--etag-' &>/dev/null; then
    curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
         -fsSLR "${asset_dwl}" \
         --etag-save "${asset_out}".etag \
         --etag-compare "${asset_out}".etag \
         --time-cond "${asset_out}" \
         --output "${asset_out}"
  else
    curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
         -fsSLR "${asset_dwl}" \
         --time-cond "${asset_out}" \
         --output "${asset_out}"
  fi

  # install
  _install_asset
}

_install_asset()
{
  # install
  local asset_path="${asset_path:-${BIN_PATH}}"
  if ! _noninteractive; then
    printf '%s ' "${_clr_orange}${FUNCNAME[2]#_ghlr_}${_clr_reset}"
  fi
  if ! diff "${asset_out}" "${asset_path}/${asset}" &>/dev/null; then
    local copied=$(cp -v "${asset_out}" "${asset_path}/${asset}")
    if [[ "${asset_path}" == "${BIN_PATH}" ]]; then
      chmod a+x "${asset_path}/${asset}"
    elif [[ "${asset_path}" == "${LIBEXEC_PATH}" ]]; then
      chmod a+x "${asset_path}/${asset}"
    else
      chmod a-x "${asset_path}/${asset}"
    fi
    # prune cache
    find . -type f \
           -name "${asset_cpf}" \
         ! -name "${asset_out}*" \
           -delete
  fi

  # output
  if ! _noninteractive; then
    if [[ -n "${copied-}" ]]; then
      printf '%s%s%s\n' \
        "${_clr_blue}" \
        "'${asset_out}' => '${asset_path}/${asset}'" \
        "${_clr_reset}"
    else
      printf '%s%s%s\n' \
        "${_clr_green}" \
        "'${asset_out}' == '${asset_path}/${asset}'" \
        "${_clr_reset}"
    fi
  else
    if [[ -n "${copied-}" ]]; then
      printf '%s\n' "${copied}"
    fi
  fi

  # postinstall
  if [[ -z ${postinstall-} ]]; then
    if [[ -n "${copied-}" ]]; then
      unset asset_url
      unset asset_out
      unset asset_rel
      unset asset_sha
      unset asset_dwl
      unset asset_cpf
      local postinstall=called
      ${FUNCNAME[2]} postinstall
    fi
    _installed add ${FUNCNAME[2]#_ghlr_}
  fi
}

_remove_asset()
{
 rm -vf "${LIBEXEC_PATH}/${asset}" \
        "${BIN_PATH}/${asset}" \
        "${BCD_PATH}/${asset}" \
        "${ZCD_PATH}/_${asset}" \
        "${FCD_PATH}/${asset}.fish"
 _installed del ${FUNCNAME[1]#_ghlr_}
}

_clean_asset()
{
  rm -vf "${asset}"-*
}

# Install dependencies
_dependencies()
{
  for i in ${@//,/ }; do
    if ! command -v ${i} &>/dev/null; then
      _ghlr_${i} install
    elif [[ ${i} == curl ]]; then
      # current static curl with etag support
      if ! curl --help http |grep -- '--etag-' &>/dev/null; then
        _ghlr_${i} install
      fi
    fi
  done
}

# Recursive group resolver
_resolve()
{
  local input=(${@//,/ }) output=()
  local -A seen
  while :; do
    local next=()
    for i in ${input[@]}; do
      if [[ -n "${seen["${i}"]+_}" ]]; then
        continue
      fi
      local name=_ghlr_${i}
      if [[ -n "${!name-}" ]]; then
        value=${!name}
        next+=(${value//,/ })
      fi
      if declare -F _ghlr_${i} >/dev/null; then
        output+=(${i})
      elif ! compgen -v _ghlr_${i} >/dev/null; then
        printf '%s %s\n%s\n' \
          "${_clr_red}${i}${_clr_reset}" \
          "${_clr_blue}was not found and cannot be installed!${_clr_reset}" \
          "💡 Check the package lists with ${_clr_orange}ghtcli ${_clr_blue}list${_clr_reset}" \
          >&2
        false # fire the trap
      fi
      seen["${i}"]=1
    done
    if [[ ${#next[@]} -ne 0 ]]; then
      input=(${next[@]})
    else
      break
    fi
  done
  printf '%s\n' "${output[@]}" |sort
}

# get app infos from github
_get_asset_info()
{
  local d="$(curl ${AUTH_HEADER:+-H "${AUTH_HEADER}"} \
    -fsSL "https://api.github.com/repos/${owner}/${repo}" \
    |jq -r "[.description, .html_url, .homepage]
            | map(select(. != null and . != \"\"))
            | join(\"\n${_clr_reset}  => \")"
  )"
  printf '%s %b\n' \
    "${_clr_orange}${FUNCNAME[1]#_ghlr_}${_clr_reset}" \
    "${_clr_blue}${d}${_clr_reset}"
}

# Manages .installed
_installed()
{
  if [[ ! -f .installed ]]; then
    rm -f .installed
    touch .installed
  fi
  sub=${1-}
  shift ||:
  case ${sub} in
    add)
      if ! grep -qxF "${1}" .installed; then
        printf '%s\n' "${1}" >>.installed
      fi
      ;;
    del)
      if grep -qxF "${1}" .installed; then
        sed "/^${1}$/d" .installed
      fi
      ;;
    list)
      xargs -n1 <.installed |sort
      ;;
    autoclean)
      if [[ ! -s .installed ]]; then
        printf '%s %s\n' \
          "${_clr_orange}Autoclean${_clr_reset}" \
          "${_clr_blue}no remaining tools detected - removing cache..${_clr_reset}"
        rm -vrf $(pwd)
      fi
      ;;
    rmdiff)
      local new_installed="$( \
        _resolve \
          $(comm -23 <(_installed list |sort) \
                     <(_resolve ${@:-_all}) |sort))"
      local cannot_removed="$( \
        comm -12 <(printf '%s\n' "${new_installed}" |sort) \
                 <(comm -12 <(_installed list |sort) \
                            <(_resolve ${@:-_all}) |sort))"
      if [[ -n ${cannot_removed-} ]]; then
        printf '%s %s\n%s\n%s\n' \
          "${_clr_red}Ignored${_clr_reset}" \
          "${_clr_blue}$(printf '%s ' ${cannot_removed})${_clr_reset}" \
          "💡 Check the package dependency groups with ${_clr_orange}ghtcli ${_clr_blue}list${_clr_reset}" \
          "💡 Or you can force the removal of ignored packages with ${_clr_orange}ghtcli ${_clr_blue}remove --force${_clr_reset}" \
          >&2
      fi
      comm -13 <(printf '%s\n' "${new_installed}" |sort) \
               <(_installed list |sort)
      ;;
    *) false ;;
  esac
}

# Check if non-interactive
_noninteractive()
{
  [[ ! -t 0 &&
     ! -t 1 &&
     ! -t 2 &&
     -z "${SSH_CONNECTION-}" ]]
}

# Autoupdates
_autoupdate()
{
  local script="${BIN_PATH@Q}/ghtcli"
  case ${1-} in
    ena*) # create cronjob
      _autoupdate marker
      if [[ ${KERNEL} == darwin ]]; then
        local job="0 */6 * * 1-5 $(which bash 2>/dev/null) ${script} update"
      else
        local job="0 */6 * * 1-5 ${script} update"
      fi
      if [[ -n "${GHTCLI_GITHUB_TOKEN}" ]]; then
        if ! (crontab -l 2>/dev/null |grep -qF GHTCLI_GITHUB_TOKEN=); then
          (crontab -l 2>/dev/null |grep -vF ${script} ||:) |crontab -
          (crontab -l 2>/dev/null |grep -vF GHTCLI_GITHUB_TOKEN= ||:; \
            printf '%s\n' "GHTCLI_GITHUB_TOKEN=${GHTCLI_GITHUB_TOKEN@Q}") |crontab -
        fi
      fi
      if ! (crontab -l 2>/dev/null |grep -qF ${script}); then
        (crontab -l 2>/dev/null |grep -vF ${script} ||:; \
          printf '%s\n' "${job}") |crontab -
        printf '%s %s %s\n' \
          "${_clr_orange}Autoupdate${_clr_reset}" \
          "${_clr_blue}${USER}${_clr_reset}" \
          'cronjob added:'
      else
        printf '%s %s %s\n' \
          "${_clr_orange}Autoupdate${_clr_reset}" \
          "${_clr_blue}${USER}${_clr_reset}" \
          'cronjob(s) already present:'
      fi
      (crontab -l 2>/dev/null |grep -F GHTCLI_GITHUB_TOKEN= ||:) \
        |xargs -rI%% printf ' %s\n' "${_clr_blue}%%${_clr_reset}"
      (crontab -l 2>/dev/null |grep -F ${script} ||:) \
        |xargs -rI%% printf ' %s\n' "${_clr_blue}%%${_clr_reset}"
      printf '%s\n' "💡 Edit the timing manually with: ${_clr_blue}crontab -eu ${_clr_orange}${USER}${_clr_reset}"
      ;;
    dis*) # remove cronjobs
      local token="$(crontab -l 2>/dev/null |grep -F GHTCLI_GITHUB_TOKEN= ||:)"
      local job="$(crontab -l 2>/dev/null |grep -F ${script} ||:)"
      if [[ -n "${job}" || -n "${token}" ]]; then
        (crontab -l 2>/dev/null |grep -vF GHTCLI_GITHUB_TOKEN= ||:) |crontab -
        (crontab -l 2>/dev/null |grep -vF ${script} ||:) |crontab -
        printf '%s %s %s\n' \
          "${_clr_orange}Autoupdate${_clr_reset}" \
          "${_clr_blue}${USER}${_clr_reset}" \
          'cronjob(s) removed:'
      else
        printf '%s %s %s\n' \
          "${_clr_orange}Autoupdate${_clr_reset}" \
          "${_clr_blue}${USER}${_clr_reset}" \
          'no cronjob(s) found.'
      fi
      printf '%s' "${token}" \
        |xargs -rI%% printf ' %s\n' "${_clr_blue}%%${_clr_reset}"
      printf '%s' "${job}" \
        |xargs -rI%% printf ' %s\n' "${_clr_blue}%%${_clr_reset}"
      if _autoupdate marker &>/dev/null; then
        rm -f "${CFG_PATH}"/autoupdate
      fi
      ;;
    mar*) # manages markers
      if [[ -e "${CFG_PATH}"/autoupdate ]]; then
        local hostname=$(head -n1 "${CFG_PATH}"/autoupdate)
        if [[ $(hostname -f) != ${hostname-} ]]; then
          printf '%s %s %s\n' \
            "${_clr_red}Autoupdate${_clr_reset}" \
            "${_clr_blue}is already enabled on host${_clr_reset}" \
            "${_clr_orange}${hostname:-🚫 ${_clr_red}marker is empty}${_clr_reset}"
            >&2
          return 1
        fi
      else
        hostname -f >"${CFG_PATH}"/autoupdate
      fi
      ;;
    *) # usage
      printf '%s\n' "Usage: ghtcli ${cmd} {enable|disable}"
      ;;
  esac
}

# List application groups
_list()
{
  local maxcols=5
  local all_groups="$(compgen -v _ghlr_ |awk '{sub(/^_ghlr_/, ""); print}')"
  for group in ${@:-${all_groups}}; do
    items=($(_resolve ${group} |tr '\n' ' '))
    if (( ${#items[@]} == 0 )); then
      continue
    fi
    for (( i=0; i<${#items[@]}; i+=maxcols )); do
      chunk=(${items[@]:i:maxcols})
      if (( i == 0 )); then
        printf '%-30s\t' \
          "${_clr_orange}${group}${_clr_reset}"
      else
        printf '%s\t\t'
      fi
      for item in ${chunk[@]}; do
        printf '%s ' \
          "${_clr_blue}${item}${_clr_reset}"
      done
      printf '\n'
    done
  done
}

# Internal application groups
_ghlr__all="$(declare -F \
  |awk '$3~/^_ghlr_/{sub(/^_ghlr_/,"",$3);print$3}')"
_ghlr__installed="$(_installed list)"
_ghlr__missing="$(comm -23 \
  <(printf '%s\n' ${_ghlr__all} |sort) \
  <(printf '%s\n' ${_ghlr__installed}) |sort)"

# Help and usage pages (needs tabs => :set noexpandtab)
_usage()
{
  cat <<-__USAGE__
		ghtcli install <tools>             # Install selected or all tools
		ghtcli postinstall <tools>         # Postinstall for selected or all tools
		ghtcli remove --force <tools>      # Remove selected or all tools
		ghtcli clean <tools>               # Clean up cached downloads
		ghtcli list <tools>                # Show all available tools or groups
		ghtcli info <tools>                # Show GitHub metadata for tools
		ghtcli update                      # Update all installed tools
		ghtcli autoupdate (enable|disable) # Enable or disable autoupdate
		ghtcli help                        # Show further infos
		__USAGE__
}

_help()
{
  cat <<-__HELP__

		ghtcli – install, update and manage Talos and Kubernetes CLI tools

		$(_usage)

		Note:
		  If <tools> is omitted, the action applies to all applicable tools.
		  Commands like update, autoupdate or help do not use <tools>.

		Supported Platforms: 🐧 Linux  🍎 macOS

		More info: https://github.com/buehr-ing/ghtcli#readme

		__HELP__
}

#
# Does the job
#

while :; do
  cmd=${1-}
  shift ||:
  case ${cmd} in
    deb*|dbg)
      set -x ;;
    lis*|ls) # list
      _list ${@-}
      break ;;
    inf*) # info
      _dependencies jq
      for i in $(_resolve ${@:-_all}); do
        _ghlr_${i} info
      done
      break ;;
    ins*) # install
      _dependencies jq
      for i in $(_resolve ${@:-_all}); do
        _ghlr_${i} install
      done
      break ;;
    pos*|com*) # postinstall (formerly completion)
      for i in ${@:-$(_installed list)}; do
        if grep -qxF ${i} .installed; then
          postinstall=called
          _ghlr_${i} postinstall
        else
          unset -v postinstall
          _ghlr_${i} install
        fi
      done
      break ;;
    upd*) # update
      if _noninteractive; then
        _autoupdate marker
      fi
      if _installed list |grep -qxF ghtcli; then
        for i in ghtcli \
          $(_installed list |(grep -vxF ghtcli ||:)); do
            _ghlr_${i} install
        done
      else
        for i in $(_installed list); do
          _ghlr_${i} install
        done
      fi
      break ;;
    rem*|rm) # remove
      if [[ "${1-}" =~ ^-?-f.*$ ]]; then
        shift ||:
        for i in $(_resolve ${@:-$(_installed list)}); do
          _ghlr_${i} remove
        done
      else
        for i in $(_installed rmdiff ${@:-_all}); do
          _ghlr_${i} remove
        done
      fi
      _installed autoclean
      break ;;
    cle*) # clean
      for i in $(_resolve ${@:-_all}); do
        _ghlr_${i} clean
      done
      break ;;
    aut*) # autoupdate
      _dependencies ghtcli
      _autoupdate ${1-}
      break ;;
    hel*) # help
      _help
      break ;;
    *)
      _usage
      break ;;
  esac
done
